### ISSUE TITLE
Browse products

### ISSUE THREAD

**Issue by Hadj-Said-Bouras** [202306-NEA-DZ-FEW/team-f#28]
**Task title**
browse products (Search and filter)

**Task description**
Create search and filter components

**Subtasks**
- [x] Create Search component
- [x] Create filter component

**Screenshots**
![image](https://github.com/ismail-benlaredj/recoded-capstone/assets/89461340/97118ade-e6e6-4a74-98d5-93fae799ba31)

**Link to the component on Figma**
[Put the link here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=106-630&mode=design&t=bCAX85VlsfTlAttZ-4)

**Comment by mohamed-cheraitia** [comment]
Create Search component
 Create filter component
